# Generated by Django 2.2.24 on 2021-08-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210818_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, editable=False, max_length=36, null=True, verbose_name='Код доступа'),
        ),
    ]
