# Generated by Django 2.2.24 on 2021-08-18 10:24

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20210818_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(help_text='Укажите год выхода произведения', validators=[reviews.models.year_validator], verbose_name='Год выхода произведения'),
        ),
    ]
