# Generated by Django 2.2.16 on 2021-08-13 13:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название категории', max_length=256, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Укажите адрес для страницы категории. Используйте только латиницу, цифры, дефисы и знаки подчёркивания', unique=True, verbose_name='Адрес')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название жанра', max_length=200, verbose_name='Название жанра')),
                ('slug', models.SlugField(help_text='Укажите адрес для страницы жанра. Используйте только латиницу, цифры, дефисы и знаки подчёркивания', unique=True, verbose_name='Адрес')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GenreTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст обзора')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальный рейтинг: 1'), django.core.validators.MaxValueValidator(10, message='Максимальный рейтинг: 10')], verbose_name='Рейтинг на основе всех отзывов')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название произведения', max_length=256, verbose_name='Название произведения')),
                ('year', models.IntegerField(help_text='Укажите год выхода произведения', verbose_name='Год выхода произведения')),
                ('rating', models.IntegerField(default=None, help_text='Укажите рейтинг произведения', null=True, verbose_name='Рейтинг произведения')),
                ('description', models.CharField(help_text='Укажите описание произведения', max_length=200, verbose_name='Описание произведения')),
                ('category', models.ForeignKey(help_text='Укажите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='categories_title', to='reviews.Category', verbose_name='Категория')),
                ('genre', models.ManyToManyField(help_text='Укажите жанр', through='reviews.GenreTitle', to='reviews.Genre', verbose_name='Жанр')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
